### PR TITLE
Add entry point to enable execution via `python -m rstcheck`

### PR DESCRIPTION
**Pull request by tempookian**
# Check List

Resolves: #<issue number here>

- [ ] I added **tests** for the changed code.
- [x] I updated the **documentation** for the changed code.
- [x] I ran the **full** `tox` test suite locally, so the CI pipelines should be green.
- [x] I added the change to the CHANGELOG.md file.

This pull request introduces a new file `__main__.py` in the `src/rstcheck` directory, creating an entry point for the `rstcheck` command line interface. This update allows for execution using `python -m rstcheck`. This change addresses an issue observed in dependent packages, where the lack of a __main__.py file broke execution attempts via python -m, as exemplified by the issue in [the Visual Studio Code extension for reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext).

### CODE REVIEW

**Comment by Cielquan** [comment]
If you fix the CI issue, I can merge the PR.

**Comment by tempookian** [comment]
> If you fix the CI issue, I can merge the PR.

Thanks for checking. I guess now, it's ready to go

**Comment by Cielquan** [comment]
Thanks for the PR. :)

**Comment by Cielquan** [comment]
I just released a new version including this PR.

**Pull request merged**
