### PR TITLE
Added support for regex

### PR DESCRIPTION
**Pull request by sameersingh7**

### CODE REVIEW

**Comment by myint** [comment]
I hesitate to add things that won't be used. Do people actually put regular expressions in their RST code blocks? I've never seen examples in the wild.

When rendering RST with `.. code:: regex`, Pygments gives me:
```
Cannot analyze code. No Pygments lexer found for "regex".
```

http://pygments.org/languages/

**Comment by jayvdb** [comment]
I've created a enhancement request for pygments : https://bitbucket.org/birkenfeld/pygments-main/issues/1341/new-lexer-request-regex ;-)

**Comment by peterjc** [comment]
The request to add regex to pygments is not here after they moved from bitbucket to github:
https://github.com/pygments/pygments/issues/1045

**Comment by Cielquan** [comment]
I think this will need to stay on hold until the pygments FR is resolved by adding the feature.

**Comment by Cielquan** [comment]
This PR got automatically closed when I rename the `master` branch to `main`.

When the upstream changes are implemented you are welcome the open a new PR into `main`.

**Pull request closed without merging**
